version: '3.8'

services:
  dtamind:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: dtamind-simple
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - UI_PORT=8080
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/storage/database.sqlite
    volumes:
      - dtamind-storage:/app/storage
      - dtamind-uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  dtamind-storage:
    driver: local
  dtamind-uploads:
    driver: local

networks:
  default:
    name: dtamind-simple-network
