version: '3.8'

services:
  dtamind:
    image: nginx:alpine
    container_name: dtamind-working
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./packages/ui/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
