version: '3.1'

services:
    redis:
        image: redis:alpine
        container_name: dtamind-redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - dtamind-net

    flowise:
        container_name: flowise-main
        build:
            context: .. # Build using the Dockerfile in the root directory
            dockerfile: docker/Dockerfile
        ports:
            - '${PORT}:${PORT}'
        volumes:
            # Mount local .dtamind to container's default location
            - ../.dtamind:/root/.dtamind
        environment:
            # --- Essential Flowise Vars ---
            - PORT=${PORT:-3000}
            - DATABASE_PATH=/root/.dtamind
            - SECRETKEY_PATH=/root/.dtamind
            - LOG_PATH=/root/.dtamind/logs
            - BLOB_STORAGE_PATH=/root/.dtamind/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=flowise-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
        networks:
            - dtamind-net

    flowise-worker:
        container_name: flowise-worker
        build:
            context: .. # Build context is still the root
            dockerfile: docker/worker/Dockerfile # Ensure this path is correct
        volumes:
            # Mount same local .dtamind to worker
            - ../.dtamind:/root/.dtamind
        environment:
            # --- Essential Flowise Vars ---
            - WORKER_PORT=${WORKER_PORT:-5566} # Port for worker healthcheck
            - DATABASE_PATH=/root/.dtamind
            - SECRETKEY_PATH=/root/.dtamind
            - LOG_PATH=/root/.dtamind/logs
            - BLOB_STORAGE_PATH=/root/.dtamind/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=flowise-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
            - flowise
        networks:
            - dtamind-net

volumes:
    redis_data:
        driver: local

networks:
    dtamind-net:
        driver: bridge
